openapi: 3.0.0
info:
  title: Self App Project
  description: >
    <div>In this Project, I have created a RESTful API
    
    </div>

    <h3> Username Table Schema </h3> 
    <table>
      <thead>
        <th>Column Name</th>
        <th>Column Type</th>
        <th>Constraints</th>
      </thead>
      <tbody>
      <tr>
        <td>user_id</td>
        <td>Integer</td>
        <td>Primary Key, Auto Increment</td>
      </tr>
      <tr>
        <td>username</td>
        <td>String</td>
        <td>Not Null, Unique</td>
      </tr>
      <tr>
        <td>password</td>
        <td>String</td>
        <td>Not Null</td>
      </tr>      
    </tbody>
    </table>

    <h3> Tracker Table Schema </h3> 
    <table>
      <thead>
        <th>Column Name</th>
        <th>Column Type</th>
        <th>Constraints</th>
      </thead>
      <tbody>
      <tr>
        <td>id</td>
        <td>Integer</td>
        <td>Primary Key, Auto Increment</td>
      </tr>
      <tr>
        <td>tracker_name</td>
        <td>String</td>
        <td> Not Null</td>
      </tr>
      <tr>
        <td>description</td>
        <td>String</td>
        <td>Not Null</td>
      </tr>  
      <tr>
        <td>tracker_type</td>
        <td>String</td>
        <td>Not Null</td>
      </tr> 
      <tr>
        <td>time</td>
        <td>String</td>
        <td></td>
      </tr> 
      <tr>
        <td>value</td>
        <td>String</td>
        <td></td>
      </tr> 
    </tbody>
    </table>
    
    <h3> Logging Table Schema </h3> 
    <table>
      <thead>
        <th>Column Name</th>
        <th>Column Type</th>
        <th>Constraints</th>
      </thead>
      <tbody>
      <tr>
        <td>log_id</td>
        <td>Integer</td>
        <td>Primary Key, Auto Increment</td>
      </tr>
      <tr>
        <td>timestamp</td>
        <td>String</td>
        <td>Not Null</td>
      </tr>
      <tr>
        <td>value</td>
        <td>String</td>
        <td>Not Null</td>
      </tr>      
      <tr>
        <td>note</td>
        <td>String</td>
        <tdNot Null></td>
      </tr> 
      <tr>
        <td>tid</td>
        <td>String</td>
        <tdNot Null></td>
      </tr> 
    </tbody>
    </table>

    <h3> User_Tracker Table Schema </h3> 
    <table>
      <thead>
        <th>Column Name</th>
        <th>Column Type</th>
        <th>Constraints</th>
      </thead>
      <tbody>
      <tr>
        <td>ut_id</td>
        <td>Integer</td>
        <td>Primary Key, Auto Increment</td>
      </tr>
      <tr>
        <td>uid</td>
        <td>Integer</td>
        <td>Foreign Key (username.uid), Not Null</td>
      </tr>
      <tr>
        <td>tid</td>
        <td>Integer</td>
        <td>Foreign Key (tracker.id), Not Null</td>
    </tbody>
    </table>
    
    <h3> Tracker_Log Table Schema </h3> 
    <table>
      <thead>
        <th>Column Name</th>
        <th>Column Type</th>
        <th>Constraints</th>
      </thead>
      <tbody>
      <tr>
        <td>tl_id</td>
        <td>Integer</td>
        <td>Primary Key, Auto Increment</td>
      </tr>
      <tr>
        <td>tid</td>
        <td>Integer</td>
        <td>Foreign Key (tracker.id), Not Null</td>
      </tr>
      <tr>
        <td>lid</td>
        <td>Integer</td>
        <td>Foreign Key (log.log_id), Not Null</td>
    </tbody>
    </table>

    <h3> Error Codes </h3> 
    <table>
      <thead>
        <th>Resource</th>
        <th>Error Code</th>
        <th>Message</th>
      </thead>
      <tbody>
      <tr>
        <td>Log</td>
        <td>LOG001</td>
        <td>TimeStamp is required and should be string </td>
      </tr>
      <tr>
        <td>Log</td>
        <td>LOG002</td>
        <td>Value is required and should be string </td>
      </tr>
      <tr>
        <td>Log</td>
        <td>LOG003</td>
        <td>Note is required and should be string </td>
      </tr>
    </tbody>
    </table>

  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000/
paths:
#   /api/trackers:
#     description: End point to crate and get deck resource
#     get:
#       description: Operation to get deck. 
#       responses:
#         '200':
#           description: Request Successful
#           content:
#             application/json:
#               schema:
#                 type: array
#                 items:
#                   properties:
#                     deck_id:
#                       type: integer
#                       example: 1
#                     deck_name:
#                       type: string
#                       example: English
#                     score:
#                       type: string
#                       example: '0'
#                     time:
#                       type: string
#                       example: 'None'
#         '404':
#           description: No Tracker Created
#         '500':
#           description: Internal Server Error    
#     post:
#       description: Operation to create the Tracker resource
#       requestBody:
#         content:
#           application/json:
#             schema:
#               type: object
#               properties:
#                 tracker_name:
#                   type: string
#                   example: Temperature Tracker
#                 description:
#                   type: string
#                   example: 'keep record of temperature'
#                 tracker_type:
#                   type: string
#                   example: Number
#       responses:
#         '201':
#           description: Successfully Created
#           content:
#             application/json:
#               schema:
#                 type: object
#                 properties:
#                   id:
#                     type: integer
#                     example: 1
#                   tracker_name:
#                     type: string
#                     example: Temperature Tracker
#                   description:
#                     type: string
#                     example: 'keep record of temperature'
#                   tracker_type:
#                     type: string
#                     example: Number
#                   value:
#                     type: string
#                     example: None
#                   time:
#                     type: string
#                     example: None

#         '500':
#           description: Internal Server Error
#         '400':
#           description: Bad request
#           content:
#             application/json:
#               schema:
#                 type: object
#                 properties:
#                   error_code:
#                     type: string
#                   error_message:
#                     type: string
                    
#   /api/trackers/{tracker_id}:
#     description: Operation to delete tracker
#     delete:
#       description: Operation to delete the tracker resource
#       parameters:
#         - in: path
#           name: tracker_id
#           required: true
#           schema:
#             type: integer
#             example: 1
#       responses:
#         '200':
#           description: Tracker Successfully Deleted
#         '500':
#           description: Internal Server Error
#         '404':
#           description: Tracker not found 
                    
  /api/log/{id}:
    description: End point to create and get log resource
    get:
      description: Operation to get card of given tracker. 
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 0
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    log_id:
                      type: integer
                      example: 1
                    timestamp:
                      type: string
                      example: "2022-09-16 20:25:09.877936+05:30"
                    value:
                      type: string
                      example: "98.6"
                    note:
                      type: string
                      example: "I was not feeling okay"
                    tid:
                      type: integer
                      example: 2
        '500':
          description: Internal Server Error
        '404':
          description: Log not found  
        '400':
          description: Invalid Tracker id
        
    post:
      description: Operation to create the Log resource
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                timestamp:
                  type: string
                  example: "2022-09-16 20:25:09.877936+05:30"
                value:
                  type: string
                  example: "98.6"
                note:
                  type: string
                  example: "I was not feeling okay"
      responses:
        '201':
          description: Successfully Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  log_id:
                    type: integer
                    example: 1
                  timestamp:
                    type: string
                    example: "2022-09-16 20:25:09.877936+05:30"
                  value:
                    type: string
                    example: "98.6"
                  note:
                    type: string
                    example: "I was not feeling okay"
                  tid:
                    type: integer
                    example: 2
        '500':
          description: Internal Server Error
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                  error_message:
                    type: string  
    delete:
      description: Delete a log
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Log deleted Successfully
        '500':
          description: Internal Server Error
        '404':
          description: Log not found 